DROP TABLE user_roles IF EXISTS;
DROP TABLE events IF EXISTS;
DROP TABLE users IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;

CREATE TABLE users
(
    id                  INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name                VARCHAR(255)            NOT NULL,
    email               VARCHAR(255)            NOT NULL,
    password            VARCHAR(255)            NOT NULL,
    registered          TIMESTAMP DEFAULT now() NOT NULL,
    enabled             BOOLEAN DEFAULT TRUE    NOT NULL
);
CREATE UNIQUE INDEX users_unique_email_idx
    ON USERS (email);

CREATE TABLE user_roles
(
    user_id             INTEGER NOT NULL,
    role                VARCHAR(255),
    CONSTRAINT user_roles_idx UNIQUE (user_id, role),
    FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE
);

CREATE TABLE events
(
    id                  INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    start_date_time     TIMESTAMP    NOT NULL,
    description         VARCHAR(255) NOT NULL,
    current_status      VARCHAR(255) NOT NULL check ( current_status in ('PLANNED', 'IN_PROGRESS', 'FINISHED', 'CANCELED')),
    user_id             INTEGER      NOT NULL,
    FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX events_unique_user_startdatetime_idx
    ON events (user_id, start_date_time)